"""remove redundant columns

Revision ID: 2f840e72ac66
Revises: 804102a61f46
Create Date: 2025-12-26 19:50:55.988932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f840e72ac66'
down_revision: Union[str, None] = '804102a61f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'images')
    op.drop_column('notes', 'files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('files', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('images', sa.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
