"""add_files_table

Revision ID: 804102a61f46
Revises: add_is_pinned_to_todos
Create Date: 2025-12-26 01:56:17.140966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804102a61f46'
down_revision: Union[str, None] = 'add_is_pinned_to_todos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    fks = inspector.get_foreign_keys('todos')
    if any(fk['name'] == 'fk_todos_group_id' for fk in fks):
        op.drop_constraint('fk_todos_group_id', 'todos', type_='foreignkey')
    
    op.create_foreign_key(None, 'todos', 'todos', ['group_id'], ['id'])
    
    columns = [col['name'] for col in inspector.get_columns('todos')]
    if 'is_group' in columns:
        op.drop_column('todos', 'is_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_group', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('fk_todos_group_id', 'todos', 'todos', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###