"""add_is_pinned_to_notes

Revision ID: 9ca5c4231ab8
Revises: add_status_task_id
Create Date: 2025-12-13 03:27:16.467931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca5c4231ab8'
down_revision: Union[str, None] = 'add_status_task_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 先添加列，允许 NULL，并设置默认值 False
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), nullable=True, server_default=sa.false()))
    # 更新所有现有记录为 False（虽然已经有默认值，但确保所有记录都有值）
    op.execute("UPDATE notes SET is_pinned = FALSE WHERE is_pinned IS NULL")
    # 然后设置为 NOT NULL
    op.alter_column('notes', 'is_pinned', nullable=False, server_default=sa.false())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_pinned')
    # ### end Alembic commands ###
