"""add status task_id to ledger_entry

Revision ID: add_status_task_id
Revises: 9f82752ac1ea
Create Date: 2025-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_status_task_id'
down_revision: Union[str, None] = '9f82752ac1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('status', sa.String(length=16), nullable=False, server_default='pending'))
    op.add_column('ledger_entries', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('ledger_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger_entries', 'updated_at')
    op.drop_column('ledger_entries', 'task_id')
    op.drop_column('ledger_entries', 'status')
    # ### end Alembic commands ###

