"""add note images files and body_md fields

Revision ID: f9f7d042d713
Revises: eefce5d67f7b
Create Date: 2025-12-09 19:38:56.343058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f7d042d713'
down_revision: Union[str, None] = 'eefce5d67f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body_md', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'files')
    op.drop_column('notes', 'images')
    op.drop_column('notes', 'body_md')
    # ### end Alembic commands ###
